name: Workflow for Codecov example-javascript
on: [push, pull_request]
jobs:
  js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      - name: Run tests and collect coverage
        continue-on-error: true
        working-directory: ./frontend
        run: npm run test:coverage
      - name: Upload coverage to Codecov
        uses: coverallsapp/github-action@v2
        with:
          github-token: awNWweFZlJkULhugYT2lDIyI0GMemB7JT
  java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Install dependencies
        working-directory: ./backend
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run tests and collect coverage
        continue-on-error: true
        working-directory: ./backend
        run: mvn -B test jacoco:report
      - name: Coveralls push (mvn)
        working-directory: ./backend
        run: mvn coveralls:report --define repoToken=awNWweFZlJkULhugYT2lDIyI0GMemB7JT

      - name: Codecov push (action)
        uses: codecov/codecov-action@v3
